### ISSUE TITLE
Feature Request: Admin/logging interface

### ISSUE THREAD

**Issue by JoeSchubert** [PiPass/blockpage#1]
I think that serving an admin/logging interface page would be a great addition.

Ideally, this page should allow whoever is running the pihole (password protected of course) to see what domains are being whitelisted temporarily. This could provide an option to permanently whitelist the domain. 

This would also serve to provide a list of all sites which have had permanent whitelist requests so that the admin could review them and whitelist or not. Ideally, if the admin declines to whitelist it the option could be disabled on the served page.

**Comment by roenw** [comment]
Thanks for the suggestion. It would probably require a MySQL/MariaDB installation somewhere, which could be too much for older Pis. I also have to make sure that this administration dashboard isn't redundant with the Pi-Hole's one.

Some stuff for the dashboard that I was thinking about:

- Currently active blocks (who, what, when, how much time left, etc.)
- Updates to PiPass software (currently these are just on the blockpage itself when an update is available)
- Change PiPass admin password, disable features, bypass password, etc.

The last bullet point will take some time to develop. Do you have any other ideas?

**Comment by JoeSchubert** [comment]
Sqlite is part of php isn't it? If I'm not mistaken, you have to specifically build/run php with a flag to even disable it.

**Comment by trixonet** [comment]
Maybe you could tie this into the web interface of PiHole?

**Comment by roenw** [comment]
@trixonet That would be cool, but every time Pi-Hole is updated, PiPass' administration panel and potentially some other files would get overwritten. Pi-Hole's developers have specifically asked me to keep PiPass separate from Pi-Hole.

We could use Sqlite, I forgot about that.

**Comment by roenw** [comment]
This won't be implemented in the next update, but hopefully we'll have a skeleton administration panel by v1.4. The next update will likely be v1.3.5 since it's incremental.
