### ISSUE TITLE
Recommendation: Allow user configuration from outside of the code.

### ISSUE THREAD

**Issue by JoeSchubert** [PiPass/blockpage#10]
I'll try to work on things as I have time... But I would recommend doing something like this:
https://github.com/yoinx/PiPass/commit/555c9dcdb8830fc7936d4bd4127b47b4ccde348f

If you make changes to the config.php as you currently have it (to say... update the version) you'll overwrite  user changes. Making the end user have to re-change their config after every update.  This allows them to make a ~/pi_pass.ini file that will store their settings and override the config.php file. If the field is undefined, it would use your default. Obviously, I only did one field here.

An additional benefit of this is that you could then just git clone/pull the repo then copy the files where they needed to be.

**Comment by JoeSchubert** [comment]
This could be closed as it was added here: https://github.com/roenw/PiPass/commit/d9e3d79b378a53e0d5c154f8e50349f0ada551b0

**Comment by yoinx** [comment]
This could be closed as it was added here: https://github.com/roenw/PiPass/commit/d9e3d79b378a53e0d5c154f8e50349f0ada551b0
