### ISSUE TITLE
Email address for permanent unblock not working

### ISSUE THREAD

**Issue by Argent999** [PiPass/blockpage#11]
I’ve (finally) gotten pipass to work and everything seems functional, but when trying to send an email requesting a permanent unblock, I currently do not get the email address I entered in the config.php to output in my email request.

My entry in the config file is as follows:

$conf['adminemail'] = "username@gmail.com";

I’m attaching two screenshots of what happens when I press the request button, one from my iPad and another from a windows PC running chrome/gmail.

![IMG_0517](https://user-images.githubusercontent.com/51110801/58523669-42e7ee00-817a-11e9-9195-e9aee4fc027a.PNG)
<img width="1112" alt="PNG image" src="https://user-images.githubusercontent.com/51110801/58523802-9fe3a400-817a-11e9-8123-a4867faa6bf2.png">

**Comment by roenw** [comment]
This is a bug, thanks for bringing it to my attention. It has been fixed in 290d672328c19da37429bf41e15634a61ee87d8a.
