### ISSUE TITLE
Lost admin page after installation

### ISSUE THREAD

**Issue by jtovar43** [PiPass/blockpage#12]
After I installed PiPass I get a 404 error when going to <pi-hole address>/admin. I removed the admin folder from /var/www/html as instructed by the installation script. Was I not supposed to remove this folder from the directory?

**Comment by roenw** [comment]
Can you clarify where it said to remove the admin directory? (This directory was not supposed to be removed)


To fix this issue, Pi-Hole must be reinstalled by using ``pihole -r``

**Comment by jtovar43** [comment]
When I first ran the installation script it said that all the files had to be removed from the directory before it could install I guess it did not mean the admin directory. I tried running `pihole -r` but I got this error `Unable to reset /var/www/html/admin, exiting installer`.

**Comment by roenw** [comment]
``pihole uninstall && curl -sSL https://install.pi-hole.net | bash``

**Comment by roenw** [comment]
When you run the PiPass installer again, please send a screenshot of the message so I can update it.

**Comment by jtovar43** [comment]
It looks like I just misread the instructions. Thank you for your help.

**Comment by jtovar43** [comment]
It looks like I just misread the instructions. Thank you for your help.
