### ISSUE TITLE
Mobile block page gets cut off

### ISSUE THREAD

**Issue by jtovar43** [PiPass/blockpage#13]
I’ve noticed that when going to a blocked site on my phone the block page gets cutoff about halfway up the page and am unable to scroll past this point. 
![IMG_5622](https://user-images.githubusercontent.com/47489748/58581946-b3e0e180-821e-11e9-8372-c8ec499b2839.jpeg)

**Comment by roenw** [comment]
I'll work on this, it should be fixed in the next update. Thanks for bringing it to my attention.

**Comment by roenw** [comment]
The bug has been fixed in d3ae68828c77aff8cba03d4a2ef707ec2bfaffa0 and will be pushed out in the next update.
