### ISSUE TITLE
Fatal error installing

### ISSUE THREAD

**Issue by kevin25761** [PiPass/blockpage#20]
Attempting new install of PiPass v1.3 on PiHole 4.3 running on Debian stretch.

I tried the solution in #4 - no joy.

PiPass installer

[ / ] Root user check...
[ + ] Root user check complete
[ / ] DR check... Please enter your web document root. (e.g. /var/www/html)
/var/www/html
[ / ] Is this the correct document root? (/var/www/html) [y/n]
y
[ + ] DR check succeeded, now installing PiPass...
[ / ] Getting current php user...
[ + ] Current php user is root.
[ / ] Building /etc/sudoers line to add...
[ / ] Checking if /etc/sudoers is already set up...
[ / ] /etc/sudoers is already set up... not performing action.
[ / ] Now making sure that your document root folder is clear...
[ + ] In document root... downloading files.
remote: Enumerating objects: 94, done.
remote: Counting objects: 100% (94/94), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 194 (delta 37), reused 84 (delta 33), pack-reused 100
Receiving objects: 100% (194/194), 52.00 KiB | 0 bytes/s, done.
Resolving deltas: 100% (70/70), done.
From https://github.com/roenw/pipass
 * [new branch]      debian     -> origin/debian
 * [new branch]      master     -> origin/master
 * [new tag]         v1.3       -> v1.3
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /root/setup.php:97
Stack trace:
#0 /root/setup.php(107): get_data('https://apps.ro...')
#1 /root/setup.php(48): install()
#2 /root/setup.php(24): preInstall()
#3 {main}
  thrown in /root/setup.php on line 97
root@Linux04:~#

**Comment by roenw** [comment]
Edit: just reread your issue. 

What version of php are you running?

**Comment by kevin25761** [comment]
I am now at php7.0. I wasnt earlier. I was able to finish the install but now I am stuck in the re-direct loop. Where is the config.php file that I need to edit?

**Comment by roenw** [comment]
> Where is the config.php file that I need to edit?

The config.php file is located in ``<webroot>/config.php``, so for example, ``/var/www/html/config.php``.

**Comment by JoeSchubert** [comment]
> Edit: just reread your issue.
> 
> What version of php are you running?


if he wasn't able to install earlier under verison 7.0, it might be worth adding a quick check at the start of the installer. 

`    if (phpversion() < "7.0") {
		echo "Your version of PHP is too low. Please update";
		//bail out of the installer.
	}
`

**Comment by kevin25761** [comment]
Installed successfully after updating to php 7
