### ISSUE TITLE
Error Updating

### ISSUE THREAD

**Issue by jtovar43** [PiPass/blockpage#22]
When I try to install the updated version I get a fatal error in the middle of the installation script but then the install seems to proceed as normal but when I check the web root no files were written by the installer.

PiPass installer

[ / ] Root user check...
[ + ] Root user check complete
[ / ] DR check... Please enter your web document root. (e.g. /var/www/html)
/var/www/html
[ / ] Is this the correct document root? (/var/www/html) [y/n]
y
[ + ] DR check succeeded, now installing PiPass...
[ / ] Getting current php user...
[ + ] Current php user is jtovar.
[ / ] Building /etc/sudoers line to add...
[ / ] Checking if /etc/sudoers is already set up...
[ / ] /etc/sudoers is already set up... not performing action.
[ / ] Now making sure that your document root folder is clear...
[ + ] In document root... downloading files.
fatal: remote origin already exists.
[ + ] Files downloaded. Selecting version v1.3
HEAD is now at a34f247 beta --> master - Update functionality (#2)
[ + ] Selected version v1.3
[ + ] Installation complete. Please set your webserver to redirect all 404 pages to the homepage (web root). This function is not automated yet.
[ + ] NOTE: Make sure you fill out config.php or you will get stuck in a redirect loop!

**Comment by npburns224** [comment]
Also having this same problem!

**Comment by JoeSchubert** [comment]
Just out of curiosity... How are you updating?

Are you running
`sudo php /var/www/html/setup/update.php`

Or whatever your webroot path is?

I only ask because I don't even see a lot of the output you have posted in the update.php file. Unless it's been modified since you initially installed.

**Comment by jtovar43** [comment]
No i’m following the instructions that came up when I clicked on “update available” on the PiPass block page. Even when I try to reinstall it I get the same error.

**Comment by JoeSchubert** [comment]
Right. I just took a look and the instructions there. It looks like they're basically just having you reinstall each time.

In step 2, you'll need to do

`sudo rm -r blockpage .git && sudo rm index.php config.php`

For it to stop failing. The .git directory is still present, so you can't just checkout new stuff into there like it's trying to do.

This will need to fixed/worked on.

**Comment by jtovar43** [comment]
Where is the .git directory located? because I can’t find it anywhere.

**Comment by JoeSchubert** [comment]
It's a hidden directory. It'll be in you webroot, which is why modifying the second command as described would work


If you ssh in, go to your webroot (probably /var/www/html ) and do `ls -la` you'll see it.

**Comment by jtovar43** [comment]
I didn't find that directory but I restarted my system ran it again and it still gave me that error along with other text that I didn't really understand but it did actually write the files to the web root this time so I was able to get it back up and running.

**Comment by roenw** [comment]
@jtovar43 Is it working now?

**Comment by jtovar43** [comment]
Yes it is working.
