### ISSUE TITLE
Discussion: configuration

### ISSUE THREAD

**Issue by JoeSchubert** [PiPass/blockpage#25]
Since this commit: https://github.com/roenw/PiPass/commit/d9e3d79b378a53e0d5c154f8e50349f0ada551b0 users have been provided the ability to configure PiPass via an ini file in their config directory (~/.config/PiPass/PiPass.ini). I think that this would be useful in that users would no longer have to modify the config.php directly running the risk of breaking code. This would also prevent having to backup/restore the config.php file during upgrades (which would, I think, make the version number never change).

Should the readme be updated to reflect this, or let it ride as advanced configuration for now?

I think that storing the user defined variables I'm this directory outside of the webroot will also come in handy with the future change of allowing permanent unblocking bias a password. The password would be stored in the home folder config rather than in webroot or having to put files randomly outside webroot.

**Comment by roenw** [comment]
I think it would be good to update the ReadMe so that people know about this. It definitely helps with convenience.
