### ISSUE TITLE
Documentation on obtaining an SSL certificate. 

### ISSUE THREAD

**Issue by Alex-Programs** [PiPass/blockpage#26]
Please change the readme to show how to obtain and implement an SSL certificate.

**Comment by plankobostjan** [comment]
@roenw do you think we should make a wiki page for this?

@AlexAndHisScripts I've followed [this](https://www.cyberciti.biz/tips/howto-lighttpd-create-self-signed-ssl-certificates.html) tutorial to obtain and implement self-signed SSL certificates. (As far as I know, you can skip setting iptables at the end of the tutorial. Works for me.)

**Comment by JoeSchubert** [comment]
I definitely support making wiki pages and linking to those from the readme for all of the cases extra info.

**Comment by roenw** [comment]
We will make a wiki page relating to this and link it on the readme. Thank you for the suggestion,
