### ISSUE TITLE
Automated email to the admin

### ISSUE THREAD

**Issue by plankobostjan** [PiPass/blockpage#27]
Is there a possibility that we automate sending email to the PiHole administrator when requesting permanent undblock?

What I mean by automate is to send a precomposed email message when the "Request permanent unblock" button is clicked, without opening up the mail client.

**Comment by JoeSchubert** [comment]
I think that would defeat the purpose to some degree. The server would basically be emailing itself from itself, so you would have no idea who submitted the request. If this is the route to head... I think it would be better to just work on the admin page, remove the email when requesting functionality, and just have it log them to the admin interface. From there, it could email a summary once a day or something if there are any requests pending.

**Comment by plankobostjan** [comment]
@yoinx good point, I agree. Implementing unblock requests using admin page sounds like a much better idea.
