### ISSUE TITLE
Email for request permanent unblock not working

### ISSUE THREAD

**Issue by npburns224** [PiPass/blockpage#31]
When requesting a permanent unblock, my default mail application opens and a new message is created with the subject line "Unblock Request," however the email address I entered into the config.php file is not automatically entered into the recipient field.
The body of the message is also blank, so I would not know what to unblock even if I typed my address manually.

**Comment by JoeSchubert** [comment]
I believe that this may have already been fixed in this commit: https://github.com/roenw/PiPass/commit/290d672328c19da37429bf41e15634a61ee87d8a

It just hasn't been in a release yet.

**Comment by nickpburns** [comment]
I saw that just a moment ago and assumed I wasn't updating to the latest version for some reason. Didn't realize that version hasn't been released yet whoops.
