### ISSUE TITLE
Add link to temporary unblock confirmation page

### ISSUE THREAD

**Issue by npburns224** [PiPass/blockpage#32]
Turning the url of the blocked page on the "unblock confirmation page" into a link would make navigating back to the site much smoother. As it stands, you have to re-type the url, or copy/paste the url into the search bar.
It's a small change, but I think it would be a great improvement.

**Comment by JoeSchubert** [comment]
Really, I think that the full URL should be getting passed when clicking to temporarily unblock, then through some scripting just redirect the user to the previous URL after a few seconds once the unblock succeeds. I agree, having to retype it is a little unnecessary.

**Comment by AlfaJackal** [comment]
Definitely agree 100%! Otherwise the solution does not feel very intuitive.
