### ISSUE TITLE
Solution: Untrusted SSL certificates

### ISSUE THREAD

**Issue by plankobostjan** [PiPass/blockpage#35]
As I've already mentioned in #33 and @roenw mentioned in [#9](https://github.com/roenw/PiPass/issues/9#issuecomment-497292269) you need to accept security exception everytime you get redirected to the blockpage (due to the self signed certificate). I did some research and found [this](https://deliciousbrains.com/ssl-certificate-authority-for-local-https-development/) tutorial on how to create your own CA and sign you certificates with it.

After some testing I've found that the tutorial works fine with a small modification.

So, these are the steps (most of them copied from the [tutorial](https://deliciousbrains.com/ssl-certificate-authority-for-local-https-development/)) to become a CA and sign your own certificates for use on local network:

**Note:** replace "pihole" in the commands below with whatever you domain name is.

### Becoming a CA

First, generate the private key:
`openssl genrsa -des3 -out myCA.key 2048`

You will be prompted for a pass phrase, which I recommend not skipping and keeping safe. The pass phrase will prevent anyone who gets your private key from generating a root certificate of their own.

Now generate a root certificate:
`openssl req -x509 -new -nodes -key myCA.key -sha256 -days 1825 -out myCA.pem`

You will be prompted for the pass phrase of your private key (that you just choose) and a bunch of questions. The answers to those questions aren’t that important.

You should now have two files: myCA.key (your private key) and myCA.pem (your root certificate).

### Installing Your Root Certificate

You need to add the root certificate (myCA.pem) to any laptops, desktops, tablets, and phones that will be accessing your HTTPS sites (blockpage in our case). This can be a bit of a pain, but the good news is that you only have to do it once. Once your root certificate is on each device, it will be good until it expires.

[In Firefox](https://wiki.wmtransfer.com/projects/webmoney/wiki/Installing_root_certificate_in_Mozilla_Firefox)
[In Chrome](https://support.securly.com/hc/en-us/articles/206081828-How-to-manually-install-the-Securly-SSL-certificate-in-Chrome)

### Creating CA-Signed Certificates

Now that you’re a CA on all of your devices, you can sign certificates for local sites that need HTTPS.

First, create a private key:
`openssl genrsa -out pihole.key 2048`

Then, create CSR:
`openssl req -new -key pihole.key -out pihole.csr`

You’ll get all the same questions as you did above and, again, your answers don’t matter.

Now create the config file for your certificate. Create new file _your_domain.ext_
Copy the text below to the file you just created.

```authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
subjectAltName = @alt_names

[alt_names]
DNS.1 = pihole
```

Replace "pihole" with whatever you've choosen for "Common Name" when creating a CSR.

Now create the certificate:
`openssl x509 -req -in pihole.csr -CA myCA.pem -CAkey myCA.key -CAcreateserial -out pihole.crt -days 1825 -sha256 -extfile pihole.ext`

You should be prompted for your CA private key pass phrase.

You should now have three files: pihole.key (the private key), pihole.csr (the certificate signing request), and pihole.crt (the signed certificate).

Now create pihole.pem file:
`cat pihole.key  pihole.crt > pihole.pem`

### Setting lighttpd to use your new certificate

First, create directory /etc/lighttpd/certs:
`sudo mkdir /etc/lighttpd/certs`

Now copy pihole.pem and pihole.crt to /etc/lighttpd/certs:
`sudo cp pihole.crt pihole.pem /etc/lighttpd/certs`

Change permissions of the files:
`sudo chmod 400 /etc/lighttpd/certs/pihole.*`

Now add following code to /etc/lighttpd/external.conf:
```
$SERVER["socket"] == "192.168.0.2:443" {
ssl.engine = "enable"
ssl.pemfile = "/etc/lighttpd/certs/pihole.pem"
ssl.ca-file = "/etc/lighttpd/certs/pihole.crt"
}
```
Replace IP above with your server's IP and change filenames to match with yours.

Test external.conf for errors:
`sudo lighttpd -t -f /etc/lighttpd/external.conf`

Restart lighttpd:
`sudo systemctl restart lighttpd`

**Comment by roenw** [comment]
@plankobostjan That's a great idea. Would you mind adding this to the wiki or do you want me to?

**Comment by plankobostjan** [comment]
@roenw Yup, no problem. I'll add this to the wiki. :)

**Comment by roenw** [comment]
Thank you :)

**Comment by plankobostjan** [comment]
@roenw I created the [wiki page](https://github.com/roenw/PiPass/wiki/Installation:-SSL-certificates). What do you think?

**Note:**
English is not my native languge therefore I apologize in advance for any grammar, spelling or other errors of this kind.

**Comment by JoeSchubert** [comment]
@plankobostjan it might be easier to just provide directions to add the certificate to the computer rather than each browser. See [here](https://manuals.gfi.com/en/kerio/connect/content/server-configuration/ssl-certificates/adding-trusted-root-certificates-to-the-server-1605.html). This allows a single command to make any browser on the computer recognize the cert.

I don't know about iPhone, but in Android this can be done under Encryption and Credentials with install from storage.

Edit: 
I also edited your page for some English flow.

**Comment by plankobostjan** [comment]
@yoinx Yes, I was already thinking about adding instructions for that too. However, there are some browsers (like Firefox) that don't use computer's certificate store. This is why I provided browser specific instructions.

Also, on Windows, you can install certificate easily just by double-clicking on it.

Anyway, I agree, it would be a good idea to add directions on adding the certificate to the computer's store.
