### ISSUE TITLE
Docker version?

### ISSUE THREAD

**Issue by Freekers** [PiPass/blockpage#37]
This is an awesome idea but I'm not a huge fan of manually modifying system files and what not.

Have you considered a Docker version of PiPass?

Kind regards.

**Comment by JoeSchubert** [comment]
@freekers I would imagine that this should work in any docker container that supports pihole. There's no reason for this project to create a docker container as this relies on PiHole to function and they would need to be in the same container, if I'm not mistaken.

Have you tried this unsuccessfully? I'm assuming that you're running pihole in a docker container? Unfortunately, I think most of us are likely running it on a pi directly.

**Comment by roenw** [comment]
I am a huge fan of Docker and I use it on most of my boxes at home, but I really can't come to see a Docker image for Pi-Hole itself being that much more useful compared to a non-Dockerized version, but really to each his own, right? The thing is that we would have to maintain a Docker image with the latest version of Pi-Hole and apply bugfixes/changes to that image as well. Unfortunately, it's just another thing for us to maintain and we don't have the time for it right now.


We have already automated the "modifying system files" in our next version's install script, and we're looking to make the install and uninstall process as easy as possible. Right now, we don't have time to maintain a Docker image, but maybe somebody in the community will!

**Comment by Freekers** [comment]
Thanks for the explanation.

@yoinx Yes I run Pihole in a Docker Container. I haven't tried PiPass yet since I saw the installation modifies system files such as the sudoers file. Since those reside in the PiHole Docker Container, the installation script will surely fail if I run it on my Docker Host. And running scripts inside a Docker Container is against the idea of the Docker ecosystem.

@roenw Understandable, but you could take the current Pihole Docker image as base and add PiPass on top of that. If PiHole's base image gets updated, so will yours. 

I'll have a look and see if I can come up with an image. It won't be anytime soon since I have two other projects that I want to finish first.

Thanks!

**Comment by roenw** [comment]
@Freekers In that case, we might look into a Docker version, as it would make installation much easier.
