### ISSUE TITLE
Some blocked websites trigger default blockpage

### ISSUE THREAD

**Issue by jtovar43** [PiPass/blockpage#39]
Some blocked websites seem to trigger the default pihole blockpage instead of the PiPass one.

**Comment by roenw** [comment]
Could you provide more details on when this happens?

**Comment by jtovar43** [comment]
I haven't been able to identify a pattern of when this occurs but this was the [most recent site](http://simple-adblock.com) it happened on.

**Comment by JoeSchubert** [comment]
Am I missing the default blockpage for pihole? I've literally never seen one.

**Comment by jtovar43** [comment]
You have to have had the blocking mode set to IP. The default block mode doesn’t show a block page.

**Comment by roenw** [comment]
I have my blocking mode set to IP as well. Are you using NGiNX or lighttpd? Can you send your configuration file for the respective web server?

**Comment by jtovar43** [comment]
I'm using lighttpd.

Here's the configuration profile: 
[lighttpd.txt](https://github.com/roenw/PiPass/files/3288086/lighttpd.txt)

**Comment by roenw** [comment]
Change ``server.error-handler-404 = "pihole/index.php"`` to ``server.error-handler-404 = "index.php"``

This is automated in the next update. I'm 95% sure this will fix the issue.
