### ISSUE TITLE
sudo: /dev/fd/63: command not found

### ISSUE THREAD

**Issue by iroQuai** [PiPass/blockpage#42]
I've got trouble trying to use update my PiPass v1.3. 

When I use the line as mentioned in the release notes (this one: <(wget -qO- https://kubrick.roen.us/pipass/scr
ipts/install.sh) ) I get the following error:
sudo: /dev/fd/63: command not found

Anyone has an idea what I can do differently?

**Comment by roenw** [comment]
You need to execute the command in its entirety. 
``bash <(wget -qO- https://kubrick.roen.us/pipass/scripts/install.sh)``

**Comment by iroQuai** [comment]
This is the result I get:

pi@pihole:~ $ sudo bash <(wget -qO- https://kubrick.roen.us/pipass/scripts/install.sh)

bash: /dev/fd/63: No such file or directory

**Comment by roenw** [comment]
There’s no need to append ``sudo``. The script will automatically elevate its system permissions. I got the same error while adding sudo.

The way this command is structured allows us to execute an **interactive** shell script, so the command must be executed exactly as its printed.
