### ISSUE TITLE
Need Help: <redirecting block pages to https>

### ISSUE THREAD

**Issue by jtovar43** [PiPass/blockpage#44]
I am trying to redirect all http requests made to my pihole including the pipass blockpage to https using this line in /etc/lighttpd/external.conf 
`$HTTP["scheme"] == "http" { url.redirect = ("" => "https://${url.authority}${url.path}${qsa}") }`

but when I implement this the result is a redirect to this unknown page. 

<img width="779" alt="Screen Shot 2019-07-02 at 3 52 47 PM" src="https://user-images.githubusercontent.com/47489748/60542335-acab6880-9ce1-11e9-9e4a-fd9a127e05ae.png">

I followed the instructions on the wiki to make the pipass page trusted and enabled SSL but I want to force everything to use SSL.

**Comment by roenw** [comment]
Hey, sorry I’ve been busy lately. 

Have you tried 
```
$HTTP["scheme"] == "http" {
    # capture vhost name with regex conditiona -> %0 in redirect pattern
    # must be the most inner block to the redirect rule
    $HTTP["host"] =~ ".*" {
        url.redirect = (".*" => "https://%0$0")
    }
}
```

**Comment by jtovar43** [comment]
Thanks this worked.
