### ISSUE TITLE
Need Help: kubrick.roen.us’s server IP address could not be found.

### ISSUE THREAD

**Issue by EcurbNosneb** [PiPass/blockpage#48]
Installation

I tried:
`bash <(wget -qO- https://kubrick.roen.us/pipass/scripts/install.sh)`
and got absolutely nothing but a new line.

In a browser:
`https://kubrick.roen.us` 
and I got:
`kubrick.roen.us’s server IP address could not be found.`

I assume this is temporary or is there an updated url?

Bruce

**Comment by roenw** [comment]
Yes, it is temporary. I was performing a name server upgrade and forgot to add back my server's entry, sorry about that.

Should be fixed now. Thanks for bringing this to my attention!
