### ISSUE TITLE
apps.roen.us/pipass/getuser returning 404

### ISSUE THREAD

**Issue by nbgibson** [PiPass/blockpage#49]
Be advised that https://apps.roen.us/pipass/getuser is 404ing out currently. https://apps.roen.us/pipass/setup still works as expected though.

**Comment by roenw** [comment]
What page is https://apps.roen.us/pipass/getuser referenced on? I can’t think of any off the top of my head.

**Comment by nbgibson** [comment]
It was listed as part of the install steps:

> For lighttpd, use server.error-handler-404 = "/index.php" (this is untested, but should work)
> 
> Execute cd ~ && wget https://apps.roen.us/pipass/getuser && mv getuser getuser.php && wget https://apps.roen.us/pipass/setup && mv setup setup.php to download the setup script and rename it.
> 
> Execute sudo php setup.php to execute the setup script.
> 
> Fill out the config.php configuration file.

But that appears to not be the case right now. Don't know if you updated that within the last minute or two or I just got a cached page or something. Disregard.

**Comment by roenw** [comment]
You got the cached page or saved page. That install script was changed long ago :)

**Comment by theeddie** [comment]
I still see it 
Execute cd ~ && wget https://apps.roen.us/pipass/getuser && mv getuser getuser.php && wget https://apps.roen.us/pipass/setup && mv setup setup.php

**Comment by roenw** [comment]
@theeddie Please refer to the install instructions listed on the [homepage](https://github.com/roenw/PiPass)
