### ISSUE TITLE
Need Help: blockpage

### ISSUE THREAD

**Issue by adrummer354** [PiPass/blockpage#54]
**Topic**
General area of PiPass: Update

**What have you already tried?**
Ran initial installer from original version and tried to update it to 1.35 after reading this thread:

https://www.reddit.com/r/pihole/comments/btp3zg/pipass_a_temporary_unblock_and_blockpage_solution/

1) changed directory to /var/www/html/pihole

Ran the following command: sudo rm -r blockpage && sudo rm index.php config.php 

got the following output: rm: cannot remove 'blockpage': No such file or directory

There is a  blockingpage.css in that location and also an index.php 

**Additional context**
None

**Relevant logs or images**
Paste outputs of commands or logfiles here. For example, the output of the PiPass installer.

**Comment by ghost** [comment]
Read the output. It tells you what the error is...
`sudo rm -r blockpage.css && sudo rm index.php config.php`

You never added the .css extension in.

**Comment by roenw** [comment]
Are you trying to update or remove PiPass? There is no “blockingpage.css” file part of PiPass as we only use inline styles.

**Comment by ghost** [comment]
> Are you trying to update or remove PiPass? There is no “blockingpage.css” file part of PiPass as we only use inline styles.
> […](#)

I made a false claim in my previous response.. my fault on that.. I think the OP is talking about pihole.

pi@pihole:~ $ ls /var/www/html/pihole/ | grep 'blockingpage.css'
**blockingpage.css**

**Comment by roenw** [comment]
Feel free to reopen the issue if this is still a problem
