### ISSUE TITLE
Need Help: install script

### ISSUE THREAD

**Issue by spotpuff** [PiPass/blockpage#56]
**Topic**
Installation

**What have you already tried?**
bash <(wget -qO- https://kubrick.roen.us/pipass/scripts/install.sh)

**Additional context**
I am running latest raspbian on an RPi 4. I have pihole already set up.

**Relevant logs or images**
When running the install script it asks for the web document root. I entered "/var/www/html".
The script then continues and fails as follows:

> Building /etc/sudoers line to add...
> Checking if /etc/sudoers is already set up...
> /etc/sudoers is already set up. No need to add another line.
> Setting up Git repository and collecting PiPass files.
> fatal: remote origin already exists.
> fatal: not a git repository (or any of the parent directories): .git
> PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /home/pi/setup.php:87
> Stack trace:
> #0 /home/pi/setup.php(97): get_data('https://apps.ro...')
> #1 /home/pi/setup.php(50): install()
> #2 /home/pi/setup.php(24): preInstall()
> #3 {main}
>   thrown in /home/pi/setup.php on line 87

**Comment by roenw** [comment]
If you’re running Debian 10 Buster, run ``sudo apt install php7.3-curl`` and retry the install script.
