### ISSUE TITLE
Need Help: Blockpage not displaying

### ISSUE THREAD

**Issue by georgeglessner** [PiPass/blockpage#57]
**Topic**
Blockpage not displaying

**What have you already tried?**
Set `BLOCKINGMODE=IP-NODATA-AAAA`, ran `sudo service pihole-FTL restart`

**Additional context**
My lighttpd.conf has `server.error-handler-404    = "/pihole/index.php"`

Set webroot to `/var/www/html` during installation script. 

`nslookup ads.google.com` results in 
```
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:	ads.google.com
Address: 192.168.0.3
```
(192.168.0.3 is my PiHole server IP)

But still just get "Server Not Found" page instead of blockpage. 

Not sure what else I need to do, any help is appreciated.

**Comment by roenw** [comment]
Just to make sure, you are using lighttpd as a webserver, not nginx or Apache?

**Comment by georgeglessner** [comment]
I am using lighttpd, correct

**Comment by roenw** [comment]
You should change the line in lighttpd to ``server.error-handler-404 = "/index.php"``

**Comment by georgeglessner** [comment]
Still getting server not found page. Ran `sudo service lighttpd restart` after changing to `server.error-handler-404 = "/index.php"`

**Comment by roenw** [comment]
Ah the problem is the ``NODATA`` for IPv6 requests. Try to change it to only ``IP`` and run ``sudo pihole restartdns``.

**Comment by georgeglessner** [comment]
Just did that and issue still persists. When setting to just `IP`, `ads.google.com` is allowed to be accessed, when before it wasn't. And `doubleclick.net` brings me to the classic server not found page still. Although, the `nslookup` for both of them point to my pihole server IP address, so not sure what the deal is.

**Comment by roenw** [comment]
What exactly is the error message on doubleclick.net? Is it ERR_NOT_RESOLVED or a 404? Also, change your FTL configuration to ``IP-AAAA`` for IPv6.

Try run an nslookup on another device on your network for safe measure.

**Comment by georgeglessner** [comment]
Ah, okay so doing the nslookup on another machine gives me an IPv6 address for both `ads.google.com` and `doubleclick.net` they are still blocked, just don't show the blockpage. 

How do I go about changing my FTL configuration to `IP-AAAA` for IPv6? Would that be in `/etc/pihole/pihole-FTL.conf`?

Edit: I do get an `ERR_NAME_NOT_RESOLVED` message

**Comment by roenw** [comment]
Yes, that would be in the PiHole-FTL.conf file.

**Comment by georgeglessner** [comment]
> Also, change your FTL configuration to IP-AAAA for IPv6

Is this just setting `BLOCKINGMODE=IP-NODATA-AAAA` ? If so, I have already tried that.

**Comment by roenw** [comment]
Remove NODATA from the config.

**Comment by georgeglessner** [comment]
That's what it is already set to. 

```
PRIVACYLEVEL=0
BLOCKINGMODE=IP-AAAA
```

**Comment by roenw** [comment]
Have you tried IP-AAAA-NODATA?

**Comment by georgeglessner** [comment]
Just tried that and ran `sudo service pihole-FTL restart` and blockpage still will not show. Just get NSURLErrorDomain on phone and on computer just takes me to my personal index.php page which just shows me my `phpinfo()` output.

**Comment by roenw** [comment]
Your webroot index.php file should be PiPass index.php. At this point I would recommend a full reinstall of PiPass before moving forward.

**Comment by georgeglessner** [comment]
Unfortunately that did not work either. I restarted everything too, lighttpd, dns, FTL, even cleared my dns on computer. I am just going to uninstall. Sorry this didn't work for me.
