### ISSUE TITLE
Feature Request: About temporary allowed access to blocked site > allow access until a certain times.

### ISSUE THREAD

**Issue by Yuri-01** [PiPass/blockpage#59]
**Feature**
Please consider ability to add new feature:
allow access until a certain imes.
For example, until the following times: 9:00, 10:00, 11:00, 12:00, 13:00, 14:00, 15:00, 16:00
And, if now - 9:10 then perform this new feature allowed access up to 10:00.
If now - 12:59 then perform this new feature allowed access up to 13:00.

**Justification**
This feature may be very useful in schools.
It is allow teachers unblock to Internet access to current/next lesson.

---
sorry for my ugly english.

**Comment by roenw** [comment]
Thank you for the suggestion, and your English is great. Currently on the roadmap we have an ability to set a passcode to unblock, so you think it would be most beneficial when the passcode lock is enabled or always? This is a good idea!

**Comment by Yuri-01** [comment]
I think, that EDU environment useful feature to teachers have ability to disable Internet-filter up to the ent current lesson (in hours/minutes - it's flexible time dependent on how much time has passed since the beginning of the current lesson.
And yes: it feature should be protected (passcode or another way).

And... thank for your work & app...

**Comment by roenw** [comment]
Added to roadmap, most likely won’t be implemented until admin panel functionality is complete, which could take a while...
