### ISSUE TITLE
Need Help: Cant install

### ISSUE THREAD

**Issue by dizzie131** [PiPass/blockpage#60]
**Topic**
Installation

**What have you already tried?**
`bash <(wget -qO- https://sputnik.roen.us/pipass/scripts/install.sh)`

**Additional context**
I installed PiPass and had it working well. Due to an unknown issue, my internet stopped working and the issue was due to PiHole... So I formatted my Pi SD card and started fresh. Installed Raspbian and Pihole. added php curl. 
Ran the install script for PiPass and it doesnt work... eg no config file added in web root folder

**Relevant logs or images**
`PiPass installer

Root user check...
Root user check complete
mv: '/home/pi/setup.php' and 'setup.php' are the same file
Please enter your web document root. (e.g. /var/www/html)
/var/www/html
Confirmation: Is this the correct document root? (/var/www/html) [y/n]
y
DR check succeeded, now installing PiPass... 
Current php user is root.
Building /etc/sudoers line to add...
Checking if /etc/sudoers is already set up...
/etc/sudoers is already set up. No need to add another line.
Setting up Git repository and collecting PiPass files.
fatal: remote origin already exists.
fatal: not a git repository (or any of the parent directories): .git
Files downloaded. Moving to latest stable release v1.3
HEAD is now at a34f247 beta --> master - Update functionality (#2)
Lighttpd web server detected. Modifying 404 redirects.
Modifying PiHole FTL to BLOCKINGMODE=IP
Selected version v1.3
rm: cannot remove '.github': No such file or directory
rm: cannot remove 'README.md': No such file or directory
rm: cannot remove 'setup': No such file or directory
rm: cannot remove 'docs': No such file or directory
rm: cannot remove 'mkdocs.yml': No such file or directory
Removed redundant files.`

**Comment by dizzie131** [comment]
I had a look at issue #51 as the error was the same, however i ran the `sudo apt update && sudo apt install php-curl' command but issue still persists.

**Comment by roenw** [comment]
Despite the error messages, it looks to me like the installation completed successfully. What's the result of ``ls -la /var/www/html``? Also, please post your lighttpd configuration file so that I can help you better.

**Comment by dizzie131** [comment]
Looks like you're right and it did install. Not sure how as I am a beginner. But thanks for getting back to me.
