### ISSUE TITLE
What is my web document root?

### ISSUE THREAD

**Issue by dhdeanha** [PiPass/blockpage#63]
I tried to follow the installation instructions but I don't know what my web document root is. I am a total noob at debian 9 stretch so help me out please.

I followed this guide to get my pihole up: https://github.com/rajannpatel/Pi-Hole-PiVPN-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-OpenVPN-Configs

**Comment by roenw** [comment]
Your web root will probably be /var/www/html.
