### ISSUE TITLE
Need Help: How do I remove PiPass

### ISSUE THREAD

**Issue by AlfaJackal** [PiPass/blockpage#64]
Could you please explain how to uninstall it? Used your script to install it. 

Thanks.

**Comment by AlfaJackal** [comment]
Found your docs...

**Comment by roenw** [comment]
The docs still have the kubrick (the old server) referenced, for anyone wondering the command is
``bash <(wget -qO- https://sputnik.roen.us/pipass/scripts/uninstall.sh)``
