### ISSUE TITLE
Need Help: Unattended install?

### ISSUE THREAD

**Issue by Freekers** [PiPass/blockpage#65]
Half a year ago, we had a short chat about a possible Docker version for PiPass (see https://github.com/roenw/PiPass/issues/37). I finally found some time to look at this. 

I see that PiPass requires at least one input variable, i.e. the location of the webroot. Is it possible to pass this argument on the commandline as well, so that the installation of PiPass becomes fully unattended?

**Comment by roenw** [comment]
With the current install script this is not an option but I am looking into changing it to a shell script since the idea of a php install script was just kinda stupid to be honest. 

This is something I’ve been thinking about for a long time but my teachers have been absolutely grilling me with homework and projects, that and club+school volleyball season has left me with little time to develop PiPass. 

Because of that, you are welcome to write your own script with this functionality and merge it into the repo and I’ll gladly help you. Sorry for the long response!

**Comment by Freekers** [comment]
No problem. I forked your repo and set the webroot to a hardcoded/static value, as it should not change within the Docker image anyway.

However, I ran into a blocking issue: It's not yet possible to set/specify the BLOCKINGMODE in the (official) Pi-hole Docker image. This is needed to enable the blocking page where PiPass relies on. 

I tried overwriting the blocking mode by volumemounting /etc/pihole/pihole-FTL.conf with the blockingmode hardcoded, but the container does not adhere to it because it's overwritten by an ENV in the container itself.

Hence I cannot continue until this is implemented in the official Pi-hole Docker image. See: https://github.com/pi-hole/docker-pi-hole/issues/318

**Comment by roenw** [comment]
So in the Pi-Hole Docker image, it will always listen to the ENV for BlockingMode over the pihole-FTL.conf file?

Is it possible to overwrite the preexisting ENV with a Docker-compose file? I use Docker to run my internal services on my server but I’m not super familiar with maintaining images, etc.

**Comment by Freekers** [comment]
I did some more digging and re-read the comment of the Pi-hole Docker developer, which got me even more confused. If I understood correctly, what he says is that it should be possible to change the blockingmode, just not on initial setup (i.e. first boot of the Docker image) since the relevant ENV is not being passed onto the `setupVars.conf` file yet.

So in other words, after initial setup, I should be able to change the blockingmode by adding either `BLOCKINGMODE=IP` or `BLOCKINGMODE=IP-AAAA-NODATA` to `/etc/pihole/pihole-FTL.conf ` [as stated in the documentation?](https://docs.pi-hole.net/ftldns/blockingmode/)

Well (as said before) I did so, but the container does not adhere to it, but I'm not sure why anymore. Before I stated it was due to some ENV being overwritten, but apparantly that's not the case since there is none yet for this specific setting. So why it's not working I don't know. 

I verified that the blockingmode setting is not respected by doing an `nslookup` for a domain on the blocklist. It should return the IP address of the Pi-hole if the blockingpage is enabled. However, it does not. Instead it replies with IP 0.0.0.0, which corresponds to blockingmode NULL (i.e. the default) and thus the blockpage (and PiPass) will never show up.

I will update the issue on the official Pi-hole Docker Github with my findings and ask the dev if this is intended behavior or that I'm doing something wrong.

**Comment by roenw** [comment]
The BLOCKINGMODE should be set to IP. Maybe the container does adhere to the variable and it is set wrong?

NULL will return 0.0.0.0, which is the default mode.
IP will return 10.96.184.5, or whatever the IP of your Pi-Hole is, assuming it is using host networking

May need to use IP-AAAA-NODATA for IPv6 issues, still looking into that

**Comment by Freekers** [comment]
BLOCKINGMODE needs to be set to either `IP` or `IP-AAAA-NODATA` for the blockpage to show up [according to the official Pi-hole documentation.](https://docs.pi-hole.net/ftldns/blockingmode/)

Even using 'host networking', the blockpage does not show up when using either `IP` or `IP-AAAA-NODATA` as BLOCKINGMODE. nslookup reports 0.0.0.0 for the domain's IP, which corresponds indeed to BLOCKINGMODE NULL, i.e. the default mode, even though it is set to something different (`IP` or `IP-AAAA-NODATA` )

**Comment by roenw** [comment]
That is interesting. Hopefully the Pi-Hole guys can help out on that issue.

**Comment by roenw** [comment]
@Freekers do you know a lot about maintaining Docker images? I know about Docker and deploy all of my applications on it but I still have a few questions about it.

**Comment by Freekers** [comment]
A lot might be an overstatement but I know a thing or two. I'm by no means a professional Docker (image) developer but have been using it for over 3 years now. Let me know what you're questions are and I might be able to help you out.

**Comment by roenw** [comment]
I was just wondering, would PiPass have to be bundled with Pi-Hole in an image? I would guess yes, and how would updating work?

Would the user just update their PiHole by using Docker-exec or would PiPass push a new image with the new Pi-Hole build?

**Comment by Freekers** [comment]
Yes, you would have to bundle Pi-hole with PiPass, since PiPass is dependent/relies on Pi-Hole to work. PiPass is not standalone IIRC.

I would base the PiPass image on the Pi-Hole docker image, i.e. the the Pi-hole docker image as base image like so:

```
FROM pihole/pihole:4.3.2-1 

RUN apt-get update && apt-get install -y php-curl wget 

RUN bash <(wget -qO- https://raw.githubusercontent.com/Freekers/PiPass/master/install.sh)
```

Should Pihole update their docker image, then it's just a matter of rebuilding the PiPass image so that it's based on the new Pihole base image and then push it to Docker Hub. Users should not run any docker-exec commands, as containers are immutable.

**Comment by roenw** [comment]
Ok, that's what I expected. Thank you.
In the coming days I will work on converting the PHP install scripts to shell/bash and then a Docker image after that.

Also, do you have any suggestions for the update system for PiPass? Currently it uses git and just pulls down the latest version and does its best to merge the local and remote copies which leads to merge conflicts. I'm not sure how this should be dealt with.

**Comment by Freekers** [comment]
Every time PiPass is updated, a new Docker image should be built and pushed to Docker Hub. No git pull/merge should be performed inside the Docker container, as Docker containers should be treated as immutable.

**Comment by roenw** [comment]
@Freekers sorry, I was talking about the update system for PiPass installed on bare-metal.

**Comment by Freekers** [comment]
Ah okay, I see. How does it result into merge conflicts? I don't see any files, beside the config.php file, that should be edited. So should a merge conflict arise, the user has changed something he shouldn't have, right? 

To avoid merge conflicts with the config.php, you could rename it to config.php.sample in the repo, so that users would have to rename it to config.php themselves.

**Comment by justinglock40** [comment]
> Yes, you would have to bundle Pi-hole with PiPass, since PiPass is dependent/relies on Pi-Hole to work. PiPass is not standalone IIRC.
> 
> I would base the PiPass image on the Pi-Hole docker image, i.e. the the Pi-hole docker image as base image like so:
> 
> ```
> FROM pihole/pihole:4.3.2-1 
> 
> RUN apt-get update && apt-get install -y php-curl wget 
> 
> RUN bash <(wget -qO- https://raw.githubusercontent.com/Freekers/PiPass/master/install.sh)
> ```
> 
> Should Pihole update their docker image, then it's just a matter of rebuilding the PiPass image so that it's based on the new Pihole base image and then push it to Docker Hub. Users should not run any docker-exec commands, as containers are immutable.

What if the image was pulled `FROM pihole/pihole` wouldn't that always pull down the latest pihole image when the container is restarted versus pulling a specific version ?

**Comment by Freekers** [comment]
No, you cannot update a container. You would have to pull the new/latest image, delete the container and recreate it with the same parameters. More details: https://ma.ttias.be/update-docker-container-latest-version/

**Comment by roenw** [comment]
I'm working on a Dockerfile for PiPass, but I am going to finish the install/update/uninstall bash scripts for 1.3.5.

**Comment by roenw** [comment]
Sorry for the delay. v1.3.5 is basically ready to be released and along with it a Docker image will be released. Would you be willing to help test it before I push it?
With the upcoming major updates (PiPass admin panel, Docker image, languages, etc.) I decided to create a Discourse forum for PiPass, so feel free to continue our conversation [there](https://forum.pipass.net).
