### ISSUE TITLE
Error: 404 on install

### ISSUE THREAD

**Issue by mihcox** [PiPass/blockpage#66]
pi@raspberrypi:/etc/lighttpd $ cd ~ && wget https://apps.roen.us/pipass/getuser && mv getuser getuser.php && wget https://apps.roen.us/pipass/setup && mv setup setup.php
--2020-03-16 13:35:36--  https://apps.roen.us/pipass/getuser
Resolving apps.roen.us (apps.roen.us)... 104.18.45.158, 104.18.44.158, 2606:4700:3036::6812:2d9e, ...
Connecting to apps.roen.us (apps.roen.us)|104.18.45.158|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-03-16 13:35:44 ERROR 404: Not Found.

**Comment by roenw** [comment]
The command you should be using is ``bash <(wget -qO- https://sputnik.roen.us/pipass/scripts/install.sh)``
