### ISSUE TITLE
Bug: Typo

### ISSUE THREAD

**Issue by TheLion** [PiPass/blockpage#67]
**Describe the bug**
Typo in /var/www/html/blockpage/index.php

Error displayed in /var/log/lighttpd/error.log
`(mod_fastcgi.c.421) FastCGI-stderr: PHP Notice:  Undefined variable: adminurl in /var/www/html/blockpage/index.php on line 103`

"$adminurl" should be "$adminemail"

**Comment by TheLion** [comment]
Never mind, already fixed through bug #31.

But it wasn't in the files i pulled today.

**Comment by roenw** [comment]
I’m converting the install/uninstall/update PHP scripts to bash scripts then I will push the new version.

**Comment by roenw** [comment]
The new version will be released in a few days. Feel free to create a thread on the [PiPass forum](https://forum.pipass.net/) if you need any more help.
