### ISSUE TITLE
404 for /PiPass/master/setup/setup.php

### ISSUE THREAD

**Issue by znrR** [PiPass/blockpage#68]
**Describe the bug**
When running the installer shell script it reports 404 for https://raw.githubusercontent.com/roenw/PiPass/master/setup/setup.php

**To Reproduce**
run the installer :-)

**Expected behavior**
installs PiPass

**Screenshots**
--2020-04-03 03:08:43--  https://raw.githubusercontent.com/roenw/PiPass/master/setup/setup.php
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-04-03 03:08:44 ERROR 404: Not Found.

**Desktop (please complete the following information):**
 - OS: ubuntu

**Comment by roenw** [comment]
Hey, right now I am working on porting the repository (previously at roenw/PiPass) to PiPass/blockpage. I am also rewriting the install, update, and uninstall scripts in bash as opposed to PHP. Until the setup script is rewritten, there's no automatic installation available, sorry about that. Hopefully the script will be done really soon. I will update you when I'm done and push the script.

**Comment by roenw** [comment]
@znrR and @Akamaru217, since writing the script is taking a bit longer than I anticipated, I've reinstated the original install script in the meantine. It should still work.

If you need any more help please create a thread on the [PiPass forum](https://forum.pipass.net/).
